import { useAraIdPreferencesStore } from "../store/araid-preferences.store";

const COPY = {
  th: {
    nav: { home: "หน้าหลัก", documents: "เอกสาร", settings: "ตั้งค่า", aria: "เมนูหลัก AraID" },
    common: { back: "ย้อนกลับ", signIn: "เข้าสู่ระบบ", signOut: "ออกจากระบบ", notAvailable: "-" },
    home: {
      greeting: "สวัสดี",
      online: "ออนไลน์",
      signedOutTitle: "ยังไม่ได้เข้าสู่ระบบ AraID",
      signedOutDescription: "กรุณาเข้าสู่ระบบด้วยเลขประจำตัวและ PIN",
      cardTitle: "บัตรประจำตัวประชาชน",
      cardSubtitle: "Identification Number",
      cardEnglishTitle: "Thai National ID Card",
      fullName: "ชื่อตัวและชื่อสกุล",
      identityNumber: "เลขประจำตัวประชาชน",
      birthDate: "วันเกิด",
      province: "จังหวัด",
      expandCard: "ขยายรูปบัตร",
      refreshCard: "รีเฟรชข้อมูลบัตร",
      services: "เมนูบริการ",
      documents: "เอกสาร",
      documentsDescription: "ดูข้อมูลเอกสารของคุณ",
      settings: "การตั้งค่า",
      settingsDescription: "จัดการการใช้งาน AraID",
    },
    documents: {
      title: "เอกสาร",
      heading: "เอกสารของคุณ",
      description: "ข้อมูลเอกสารที่เชื่อมกับ AraID",
      idCard: "บัตรประจำตัวประชาชน",
      houseRegistration: "ทะเบียนบ้าน",
      missingAddress: "ยังไม่มีข้อมูลที่อยู่",
    },
    settings: {
      title: "การตั้งค่า",
      heading: "บัญชีและแอปพลิเคชัน",
      description: "จัดการภาษา สถานะบัญชี และข้อมูล AraID",
      accountStatus: "สถานะบัญชี",
      signedIn: "เข้าสู่ระบบแล้ว",
      signedOut: "ยังไม่ได้เข้าสู่ระบบ",
      language: "ภาษา",
      languageDescription: "ภาษาที่ใช้แสดงผลใน AraID",
      thai: "ไทย",
      english: "English",
      about: "เกี่ยวกับ AraID",
      aboutDescription: "ข้อมูลแอปพลิเคชัน AraID",
      aboutBody: "AraID ใช้สำหรับยืนยันตัวตนและแสดงข้อมูลเอกสารที่จัดการไว้ในระบบ",
      chooseLanguage: "เลือกภาษาแสดงผล",
    },
  },
  en: {
    nav: { home: "Home", documents: "Documents", settings: "Settings", aria: "AraID main navigation" },
    common: { back: "Back", signIn: "Sign in", signOut: "Sign out", notAvailable: "-" },
    home: {
      greeting: "Hello",
      online: "Online",
      signedOutTitle: "You are not signed in to AraID",
      signedOutDescription: "Sign in with your identity number and PIN",
      cardTitle: "National ID Card",
      cardSubtitle: "Identification Number",
      cardEnglishTitle: "Thai National ID Card",
      fullName: "Full name",
      identityNumber: "Identity number",
      birthDate: "Date of birth",
      province: "Province",
      expandCard: "Expand card",
      refreshCard: "Refresh card",
      services: "Services",
      documents: "Documents",
      documentsDescription: "View your linked documents",
      settings: "Settings",
      settingsDescription: "Manage your AraID experience",
    },
    documents: {
      title: "Documents",
      heading: "Your documents",
      description: "Documents linked to your AraID profile",
      idCard: "National ID Card",
      houseRegistration: "House registration",
      missingAddress: "No address information",
    },
    settings: {
      title: "Settings",
      heading: "Account and application",
      description: "Manage language, account status, and AraID information",
      accountStatus: "Account status",
      signedIn: "Signed in",
      signedOut: "Not signed in",
      language: "Language",
      languageDescription: "Language used throughout AraID",
      thai: "ไทย",
      english: "English",
      about: "About AraID",
      aboutDescription: "AraID application information",
      aboutBody: "AraID verifies your identity and displays documents managed in this system.",
      chooseLanguage: "Choose display language",
    },
  },
} as const;

export function useAraIdCopy() {
  const language = useAraIdPreferencesStore((state) => state.language);
  return { language, copy: COPY[language] };
}
